version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: fintrace_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fintrace_admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: fintrace
    ports:
      - "5432:5432"
    volumes:
      - fintrace_pg_data:/var/lib/postgresql/data

volumes:
  fintrace_pg_data:
