"""add_asset_prices_table

Revision ID: 7e18dc4ed520
Revises: 8d547d47fe3e
Create Date: 2026-06-21 15:13:23.942846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e18dc4ed520'
down_revision: Union[str, Sequence[str], None] = '8d547d47fe3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'price_date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_asset_prices_price_date'), 'asset_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_asset_prices_ticker'), 'asset_prices', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_prices_ticker'), table_name='asset_prices')
    op.drop_index(op.f('ix_asset_prices_price_date'), table_name='asset_prices')
    op.drop_table('asset_prices')
    # ### end Alembic commands ###
