"""Add portfolio_position_snapshots

Revision ID: 43ab8666976e
Revises: 7e18dc4ed520
Create Date: 2026-06-23 12:28:20.247257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43ab8666976e'
down_revision: Union[str, Sequence[str], None] = '7e18dc4ed520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=False)
    op.create_table('portfolio_position_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshot_date')
    )
    op.create_index(op.f('ix_portfolio_position_snapshots_snapshot_date'), 'portfolio_position_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_position_snapshots_snapshot_date'), table_name='portfolio_position_snapshots')
    op.drop_table('portfolio_position_snapshots')
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
