"""Add phase 2 behavioral metrics

Revision ID: 51a0214e68ba
Revises: c9427ee4672b
Create Date: 2026-06-23 14:01:27.232198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a0214e68ba'
down_revision: Union[str, Sequence[str], None] = 'c9427ee4672b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavioral_analysis_snapshots', sa.Column('revenge_trade_count', sa.Integer(), nullable=False))
    op.add_column('behavioral_analysis_snapshots', sa.Column('panic_sell_score', sa.Float(), nullable=False))
    op.add_column('behavioral_analysis_snapshots', sa.Column('endowment_trap_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavioral_analysis_snapshots', 'endowment_trap_count')
    op.drop_column('behavioral_analysis_snapshots', 'panic_sell_score')
    op.drop_column('behavioral_analysis_snapshots', 'revenge_trade_count')
    # ### end Alembic commands ###
