"""initial_fintrace_schema

Revision ID: 8d547d47fe3e
Revises: 
Create Date: 2026-06-21 12:17:48.146590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d547d47fe3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_engines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('math_library_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax_method', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('state_differential', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tax_jurisdiction', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('calculation_engine_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_invested_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_current_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_absolute_return', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['calculation_engine_id'], ['calculation_engines.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('brokerage_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index(op.f('ix_transaction_ledger_ticker'), 'transaction_ledger', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_ledger_ticker'), table_name='transaction_ledger')
    op.drop_table('transaction_ledger')
    op.drop_table('portfolio_snapshots')
    op.drop_table('portfolios')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('calculation_engines')
    # ### end Alembic commands ###
