"""Add corporate action events

Revision ID: aaa08e8d142d
Revises: 43ab8666976e
Create Date: 2026-06-23 15:14:10.625007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa08e8d142d'
down_revision: Union[str, Sequence[str], None] = '43ab8666976e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metadata',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_asset_metadata_ticker'), 'asset_metadata', ['ticker'], unique=False)
    op.create_table('benchmark_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benchmark_name', sa.String(length=64), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('sector_weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sector_return', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_tri', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_name', 'price_date', 'sector', name='uq_benchmark_date_sector')
    )
    op.create_index(op.f('ix_benchmark_index_benchmark_name'), 'benchmark_index', ['benchmark_name'], unique=False)
    op.create_index(op.f('ix_benchmark_index_price_date'), 'benchmark_index', ['price_date'], unique=False)
    op.create_table('corporate_action_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('adjustment_factor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ex_date', 'action_type', name='uq_corp_action_ticker_date')
    )
    op.create_index(op.f('ix_corporate_action_events_ex_date'), 'corporate_action_events', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_action_events_ticker'), 'corporate_action_events', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_action_events_ticker'), table_name='corporate_action_events')
    op.drop_index(op.f('ix_corporate_action_events_ex_date'), table_name='corporate_action_events')
    op.drop_table('corporate_action_events')
    op.drop_index(op.f('ix_benchmark_index_price_date'), table_name='benchmark_index')
    op.drop_index(op.f('ix_benchmark_index_benchmark_name'), table_name='benchmark_index')
    op.drop_table('benchmark_index')
    op.drop_index(op.f('ix_asset_metadata_ticker'), table_name='asset_metadata')
    op.drop_table('asset_metadata')
    # ### end Alembic commands ###
