"""Add BehavioralAnalysisSnapshot

Revision ID: c9427ee4672b
Revises: 43ab8666976e
Create Date: 2026-06-23 13:28:14.121271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9427ee4672b'
down_revision: Union[str, Sequence[str], None] = '43ab8666976e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_analysis_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('disposition_ratio', sa.Float(), nullable=False),
    sa.Column('momentum_bias_score', sa.Float(), nullable=False),
    sa.Column('detailed_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', name='uq_behavioral_portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behavioral_analysis_snapshots')
    # ### end Alembic commands ###
