"""Add PortfolioRiskSnapshot

Revision ID: d6843d93010f
Revises: 84e71f353ab0
Create Date: 2026-06-23 21:54:19.363951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6843d93010f'
down_revision: Union[str, Sequence[str], None] = '84e71f353ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_risk_snapshots',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('beta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('annualised_volatility', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sortino_ratio', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('holding_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_risk_snapshots')
    # ### end Alembic commands ###
