"""Add phase 3 and 4 behavioral metrics

Revision ID: f02ed429ae7c
Revises: 51a0214e68ba
Create Date: 2026-06-23 14:47:47.021347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02ed429ae7c'
down_revision: Union[str, Sequence[str], None] = '51a0214e68ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metadata',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_asset_metadata_ticker'), 'asset_metadata', ['ticker'], unique=False)
    op.create_table('benchmark_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benchmark_name', sa.String(length=64), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('sector_weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sector_return', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_tri', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_name', 'price_date', 'sector', name='uq_benchmark_date_sector')
    )
    op.create_index(op.f('ix_benchmark_index_benchmark_name'), 'benchmark_index', ['benchmark_name'], unique=False)
    op.create_index(op.f('ix_benchmark_index_price_date'), 'benchmark_index', ['price_date'], unique=False)
    op.create_table('corporate_action_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('adjustment_factor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ex_date', 'action_type', name='uq_corp_action_ticker_date')
    )
    op.create_index(op.f('ix_corporate_action_events_ex_date'), 'corporate_action_events', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_action_events_ticker'), 'corporate_action_events', ['ticker'], unique=False)
    op.add_column('behavioral_analysis_snapshots', sa.Column('churn_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('win_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('winner_avg_capital', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('loser_avg_capital', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('holding_period_variance', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('overconfidence_bias_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('dividend_trap_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('bandwagon_bias_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('market_timing_futility_delta', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('behavioral_analysis_snapshots', sa.Column('boredom_trade_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavioral_analysis_snapshots', 'boredom_trade_count')
    op.drop_column('behavioral_analysis_snapshots', 'market_timing_futility_delta')
    op.drop_column('behavioral_analysis_snapshots', 'bandwagon_bias_count')
    op.drop_column('behavioral_analysis_snapshots', 'dividend_trap_count')
    op.drop_column('behavioral_analysis_snapshots', 'overconfidence_bias_count')
    op.drop_column('behavioral_analysis_snapshots', 'holding_period_variance')
    op.drop_column('behavioral_analysis_snapshots', 'loser_avg_capital')
    op.drop_column('behavioral_analysis_snapshots', 'winner_avg_capital')
    op.drop_column('behavioral_analysis_snapshots', 'win_rate')
    op.drop_column('behavioral_analysis_snapshots', 'churn_rate')
    op.drop_index(op.f('ix_corporate_action_events_ticker'), table_name='corporate_action_events')
    op.drop_index(op.f('ix_corporate_action_events_ex_date'), table_name='corporate_action_events')
    op.drop_table('corporate_action_events')
    op.drop_index(op.f('ix_benchmark_index_price_date'), table_name='benchmark_index')
    op.drop_index(op.f('ix_benchmark_index_benchmark_name'), table_name='benchmark_index')
    op.drop_table('benchmark_index')
    op.drop_index(op.f('ix_asset_metadata_ticker'), table_name='asset_metadata')
    op.drop_table('asset_metadata')
    # ### end Alembic commands ###
